# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QFileDialog

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(988, 797)

        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.MainFrame = QtWidgets.QFrame(self.centralwidget)
        self.MainFrame.setGeometry(QtCore.QRect(225, 50, 500, 500))
        self.MainFrame.setMinimumSize(QtCore.QSize(500, 500))
        self.MainFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.MainFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.MainFrame.setObjectName("MainFrame")

        self.verticalLayout = QtWidgets.QVBoxLayout(self.MainFrame)
        self.verticalLayout.setObjectName("verticalLayout")

        self.ImageFrame = QtWidgets.QFrame(self.MainFrame)
        self.ImageFrame.setMinimumSize(QtCore.QSize(0, 350))
        self.ImageFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.ImageFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ImageFrame.setObjectName("ImageFrame")

        self.gridLayout = QtWidgets.QGridLayout(self.ImageFrame)
        self.gridLayout.setObjectName("gridLayout")

        self.image_container = QtWidgets.QLabel(self.ImageFrame)
        self.image_container.setText("")
        self.image_container.setObjectName("image_container")

        self.gridLayout.addWidget(self.image_container, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.ImageFrame)

        self.ButtonFrame = QtWidgets.QFrame(self.MainFrame)
        self.ButtonFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.ButtonFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ButtonFrame.setObjectName("ButtonFrame")
        
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.ButtonFrame)
        self.horizontalLayout.setObjectName("horizontalLayout")

        self.OpenFileButton = QtWidgets.QPushButton(self.ButtonFrame)
        self.OpenFileButton.setObjectName("OpenFileButton")

        self.horizontalLayout.addWidget(self.OpenFileButton)
        self.removeFileButton = QtWidgets.QPushButton(self.ButtonFrame)
        self.removeFileButton.setObjectName("removeFileButton")

        self.horizontalLayout.addWidget(self.removeFileButton)
        self.verticalLayout.addWidget(self.ButtonFrame)

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 988, 22))
        self.menubar.setObjectName("menubar")

        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        # Connect the buttons to the functions
        self.OpenFileButton.clicked.connect(self.open_file)
        self.removeFileButton.clicked.connect(self.remove_file)


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.OpenFileButton.setText(_translate("MainWindow", "Open File"))
        self.removeFileButton.setText(_translate("MainWindow", "Remove File"))

    def open_file(self):
         # Open a file dialog to select an image
        file_path, _ = QFileDialog.getOpenFileName(None, "Open Image File", "", "Image Files (*.png *.jpg *.jpeg)")
        if file_path:
            # Load the image and display it
            pixmap = QtGui.QPixmap(file_path)
            self.image_container.setPixmap(pixmap)

            # Store the file path for further processing
            self.file_path = file_path
    
    def remove_file(self):
        # Remove the image from the label
        self.image_container.clear()
        # Clear the file path
        self.file_path = None

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
